name: savings_app
description: "AI Powered Saving App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/logo.png
    - ./.env
  uses-material-design: true
